spring.application.name=Url-Shortener
spring.config.import=optional:file:.env[.properties]

# MySQL (primary datasource — shard 0)
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_SHARD_0_PORT:3308}/${MYSQL_DATABASE:url_shortener}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${MYSQL_ROOT_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
